# Generated by Django 2.2.6 on 2019-11-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_notification_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='rainfall_duration',
        ),
        migrations.RemoveField(
            model_name='record',
            name='rainfall_intensity',
        ),
    ]
